version: '3.8'

services:
  blue-consumer:
    build:
      context: .
      dockerfile: docker/Dockerfile.blueMessageConsumer
    depends_on:
      activemq:
        condition: service_healthy
    environment:
      - ACTIVEMQ_HOST=activemq
      - ACTIVEMQ_PORT=61616

  red-consumer:
    build:
      context: .
      dockerfile: docker/Dockerfile.redMessageConsumer
    depends_on:
      activemq:
        condition: service_healthy
    environment:
      - ACTIVEMQ_HOST=activemq
      - ACTIVEMQ_PORT=61616

  green-consumer:
    build:
      context: .
      dockerfile: docker/Dockerfile.greenMessageConsumer
    depends_on:
      activemq:
        condition: service_healthy
    environment:
      - ACTIVEMQ_HOST=activemq
      - ACTIVEMQ_PORT=61616

  color-message-producer:
    build:
      context: .
      dockerfile: docker/Dockerfile.colorMessageProducer
    depends_on:
      activemq:
        condition: service_healthy
    environment:
      - ACTIVEMQ_HOST=activemq
      - ACTIVEMQ_PORT=61616

  color-statistics-consumer:
    build:
      context: .
      dockerfile: docker/Dockerfile.colorStatisticsConsumer
    depends_on:
      activemq:
        condition: service_healthy
    environment:
      - ACTIVEMQ_HOST=activemq
      - ACTIVEMQ_PORT=61616

  dead-letter-queue-consumer:
    build:
      context: .
      dockerfile: docker/Dockerfile.deadLetterQueueConsumer
    depends_on:
      activemq:
        condition: service_healthy
    environment:
      - ACTIVEMQ_HOST=activemq
      - ACTIVEMQ_PORT=61616

  activemq:
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ACTIVEMQ_USER=admin
      - ACTIVEMQ_PASSWORD=admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161"]
      interval: 10s
      timeout: 5s
      retries: 5
